//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_question
    {
        public int q_id { get; set; }

        [Display(Name ="Câu hỏi")]
        [Required(ErrorMessage ="*")]
        public string q_text { get; set; }
        [Display(Name = "Đáp án A")]
        [Required(ErrorMessage = "*")]
        public string QA { get; set; }
        [Display(Name = "Đáp án B")]
        [Required(ErrorMessage = "*")]
        public string QB { get; set; }
        [Display(Name = "Đáp án C")]
        [Required(ErrorMessage = "*")]
        public string QC { get; set; }
        [Display(Name = "Đáp án D")]
        [Required(ErrorMessage = "*")]
        public string QD { get; set; }
        [Display(Name = "Đáp án đúng")]
        [Required(ErrorMessage = "*")]
        public string QCorrectAns { get; set; }

        [Display(Name = "Select")]
        [Required(ErrorMessage = "*")]
        public Nullable<int> q_fk_catid { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
    }
}
